testfile <- fs::file_temp(ext = "Rmd")
fs::file_copy("test.Rmd", testfile)
rmarkdown::render(testfile)
dir_cache <- fs::path_file(testfile)
dir_cache <- fs::path_ext_remove(dir_cache)
dir_cache <- paste0(dir_cache, "_cache")
dir_cache <- fs::path(fs::path_dir(testfile), dir_cache)
stopifnot(fs::dir_exists(dir_cache))
fs::dir_ls(dir_cache, recurse = TRUE)
fs::dir_delete(dir_cache)
stopifnot(!fs::dir_exists(dir_cache))
